stages:
  - unit_test
test_job:
  stage: unit_test
  script:
    - echo "Running unit tests with pyTest ..."
    - pip install pytest
    - pytest ./my_service/calculator_test.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#    - merge_requests